title: David Whitlock - Elixir, Python, etc. developer
email: alovedalongthe@gmail.com
description: >
  Information about me and some of the projects I maintain.
  Elixir and Python, amongst others.
url: "https://riverrun.github.io"
author: David Whitlock
twitter_username: alovedalongthe
github_username: riverrun

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
